---
branches:
  - main
repositoryUrl: https://github.com/liatrio/github-action-conventional-release.git
preset: conventionalcommits
tagFormat: "v${version}"
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - path: '@semantic-release/github'
    failComment: false
    successComment: false
